---
title: "345 midterm"
author: "Colin Kalsbeek"
date: "3/29/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r force = T}
# get libraries 
library(tidyverse)
install.packages("devtools")

devtools::install_github("abresler/nbastatR", force = T)
library(nbastatR)

nbastatR %>% teams_shots(teams == "Milwuakee Bucks")

```
color = green 
make it opaque
miss = x (and/or red)



```{r}
# find info 
# scan websites for info


```


```{r}
## geom_path(data=data.frame(x=c(-25,25),y=c(0,0)))+

## geom_path(data=data.frame(x=c(-6000:(-1)/1000,1:6000/1000),y=c(sqrt(6^2-c(-6000:(-1)/1000## ,1:6000/1000)^2))),aes(x=x,y=y))+

## geom_path(data=data.frame(x=c(-6000:(-1)/1000,1:6000/1000),y=c(28-sqrt(6^2-c(-6000:(-1)/1000,1:6000/1000)^2))),aes(x=x,y=y))+

# geom_path(data=data.frame(x=c(-6000:(-1)/1000,1:6000/1000),y=c(28+sqrt(6^2-c(-6000:(-1)/1000,1:6000/1000)^2))),aes(x=x,y=y),linetype='dashed')+

# geom_path(data=data.frame(x=c(-8,-8,8,8,-8),y=c(47,28,28,47,47)))+

# geom_path(data=data.frame(x=c(-6,-6,6,6,-6),y=c(47,28,28,47,47)))+

# geom_path(data=data.frame(x=c(-4000:(-1)/1000,1:4000/1000),y=c(41.25-sqrt(4^2-c(-4000:(-1)/1000,1:4000/1000)^2))),aes(x=x,y=y))+

# geom_path(data=data.frame(x=c(-750:(-1)/1000,1:750/1000,750:1/1000,-1:-750/1000),y=c(c(41.75+sqrt(0.75^2-c(-750:(-1)/1000,1:750/1000)^2)),c(41.75-sqrt(0.75^2-c(750:1/1000,-1:-750/1000)^2)))),aes(x=x,y=y))+

# geom_path(data=data.frame(x=c(-3,3),y=c(43,43)),lineend='butt')+

# geom_path(data=data.frame(x=c(-22,-22,-22000:(-1)/1000,1:22000/1000,22,22),y=c(47,47-169/12,41.75-sqrt(23.75^2-c(-22000:(-1)/1000,1:22000/1000)^2),47-169/12,47)),aes(x=x,y=y))+
```
additional graphic = cool 
ideas: 
% made in worst year / % made in champ year. 
  show where in the court came more effective
  
placeholder
